export const CodeMirrorThemes = [
    { label: 'ABCDEF', key: 'abcdef' },
    { label: 'Android Studio', key: 'androidstudio' },
    { label: 'Atom One', key: 'atomone' },
    { label: 'Aura', key: 'aura' },
    { label: 'Basic', key: 'basic' },
    { label: 'BBEdit', key: 'bbedit' },
    { label: 'Bespin', key: 'bespin' },
    { label: 'Darcula', key: 'darcula' },
    { label: 'Dracula', key: 'dracula' },
    { label: 'Duotone', key: 'duotone' },
    { label: 'Eclipse', key: 'eclipse' },
    { label: 'GitHub', key: 'github' },
    { label: 'Gruvbox Dark', key: 'gruvboxDark' },
    { label: 'Material', key: 'material' },
    { label: 'Noctis Lilac', key: 'noctisLilac' },
    { label: 'Nord', key: 'nord' },
    { label: 'Okaidia', key: 'okaidia' },
    { label: 'Quiet Light', key: 'quietlight' },
    { label: 'Red', key: 'red' },
    { label: 'Solarized', key: 'solarized' },
    { label: 'Sublime', key: 'sublime' },
    { label: 'Tokyo Night', key: 'tokyoNight' },
    { label: 'Tokyo Night Storm', key: 'tokyoNightStorm' },
    { label: 'Tokyo Night Day', key: 'tokyoNightDay' },
    { label: 'VSCode', key: 'vscode' },
    { label: 'Xcode', key: 'xcode' },
];
  